version: "3.8"

services:
  postgres:
    container_name: postgres
    image: postgres
    env_file:
      - .env
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./init/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - assessment-may-2024

  redis:
    image: redis
    restart: always
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - assessment-may-2024
  
networks:
  assessment-may-2024:
    driver: bridge
    name: assessment-may-2024

volumes:
  postgres-data: