// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: daftar_pelanggan.sql

package sqlc

import (
	"context"
)

const getPelanggan = `-- name: GetPelanggan :one
SELECT id, nama, nik, nomor_hp, pin FROM daftar_Pelanggan
WHERE id = $1
`

func (q *Queries) GetPelanggan(ctx context.Context, id int64) (DaftarPelanggan, error) {
	row := q.db.QueryRowContext(ctx, getPelanggan, id)
	var i DaftarPelanggan
	err := row.Scan(
		&i.ID,
		&i.Nama,
		&i.Nik,
		&i.NomorHp,
		&i.Pin,
	)
	return i, err
}
