// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: daftar_akun.sql

package sqlc

import (
	"context"
)

const getDaftarAkun = `-- name: GetDaftarAkun :one
SELECT id, id_pelanggan, nomor_rekening, saldo FROM daftar_akun
WHERE nomor_rekening = $1
`

func (q *Queries) GetDaftarAkun(ctx context.Context, nomorRekening string) (DaftarAkun, error) {
	row := q.db.QueryRowContext(ctx, getDaftarAkun, nomorRekening)
	var i DaftarAkun
	err := row.Scan(
		&i.ID,
		&i.IDPelanggan,
		&i.NomorRekening,
		&i.Saldo,
	)
	return i, err
}

const updateSaldo = `-- name: UpdateSaldo :one
UPDATE daftar_akun
SET saldo = $2
WHERE nomor_rekening = $1
RETURNING id, id_pelanggan, nomor_rekening, saldo
`

type UpdateSaldoParams struct {
	NomorRekening string `json:"nomor_rekening"`
	Saldo         int64  `json:"saldo"`
}

func (q *Queries) UpdateSaldo(ctx context.Context, arg UpdateSaldoParams) (DaftarAkun, error) {
	row := q.db.QueryRowContext(ctx, updateSaldo, arg.NomorRekening, arg.Saldo)
	var i DaftarAkun
	err := row.Scan(
		&i.ID,
		&i.IDPelanggan,
		&i.NomorRekening,
		&i.Saldo,
	)
	return i, err
}
