// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package sqlc

import (
	"context"
)

type Querier interface {
	CreateTransaksi(ctx context.Context, arg CreateTransaksiParams) (DaftarTransaksi, error)
	GetDaftarAkun(ctx context.Context, nomorRekening string) (DaftarAkun, error)
	GetDaftarTransaksi(ctx context.Context, nomorRekening string) ([]DaftarAkun, error)
	GetPelanggan(ctx context.Context, id string) (DaftarPelanggan, error)
	UpdateSaldo(ctx context.Context, arg UpdateSaldoParams) (DaftarAkun, error)
}

var _ Querier = (*Queries)(nil)
