// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: mutasi.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createMutasi = `-- name: CreateMutasi :one
INSERT INTO mutasi (
    id,
    jenis_transaksi,
    nominal,
    nomor_rekening
) VALUES (
     $1, $2, $3,$4
) RETURNING id, nomor_rekening, jenis_transaksi, nominal
`

type CreateMutasiParams struct {
	ID             string         `json:"id"`
	JenisTransaksi sql.NullString `json:"jenis_transaksi"`
	Nominal        sql.NullInt64  `json:"nominal"`
	NomorRekening  sql.NullString `json:"nomor_rekening"`
}

func (q *Queries) CreateMutasi(ctx context.Context, arg CreateMutasiParams) (Mutasi, error) {
	row := q.db.QueryRowContext(ctx, createMutasi,
		arg.ID,
		arg.JenisTransaksi,
		arg.Nominal,
		arg.NomorRekening,
	)
	var i Mutasi
	err := row.Scan(
		&i.ID,
		&i.NomorRekening,
		&i.JenisTransaksi,
		&i.Nominal,
	)
	return i, err
}
