// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package sqlc

import (
	"context"
)

type Querier interface {
	CreateMutasi(ctx context.Context, arg CreateMutasiParams) (Mutasi, error)
}

var _ Querier = (*Queries)(nil)
